// Generated by CoffeeScript 1.3.3
(function() {

  String.prototype.truncate = function() {
    return this.replace(/\s+$/, "");
  };

  $('#search_box').keypress(function(e) {
    var keywords;
    if (e.keyCode === 13) {
      keywords = $(this).attr('value').truncate();
      if (keywords != null) {
        return $.ajax({
          url: "http://127.0.0.1:8000/search?q=" + encodeURIComponent(keywords),
          success: function(data, status, xhr) {
            return $.get("result.temp.html", function(template) {
              var result;
              result = $.mustache(template, data);
              if (result != null) {
                return $('#results').append(result);
              }
            });
          }
        });
      }
    }
  });

}).call(this);
