// Generated by CoffeeScript 1.3.3
(function() {
  var FOLLOWERS_LOW_LIMIT, access_token, analyze, app_key, emitter, events, http, https, server, users, weibo_host_v1, weibo_host_v2;

  http = require('http');

  https = require('https');

  events = require('events');

  emitter = new events.EventEmitter();

  weibo_host_v1 = "api.t.sina.com.cn";

  weibo_host_v2 = "api.weibo.com";

  app_key = "3805062853";

  access_token = "2.00qE4goBVfeVJE34ddea717fCynh5D";

  FOLLOWERS_LOW_LIMIT = 500;

  users = [];

  server = http.createServer(function(req, resp) {
    var client, keywords, options;
    keywords = require('url').parse(req.url, true)['query']['q'];
    console.log("Query keyword is " + keywords);
    if (keywords != null) {
      options = {
        host: weibo_host_v1,
        path: "/search.json?source=" + app_key + "&q=" + keywords
      };
      client = http.request(options, function(res) {
        var raw;
        res.setEncoding('utf8');
        raw = "";
        res.on('data', function(chunk) {
          return raw += chunk;
        });
        return res.on('end', function() {
          var content, weibo, _i, _len, _results;
          content = JSON.parse(raw)['results'];
          if (content != null) {
            emitter.on("all-user-info-ready", function() {
              var data, weibo;
              content = (function() {
                var _i, _len, _results;
                _results = [];
                for (_i = 0, _len = content.length; _i < _len; _i++) {
                  weibo = content[_i];
                  if (weibo['user_followers_count'] >= FOLLOWERS_LOW_LIMIT) {
                    _results.push(weibo);
                  }
                }
                return _results;
              })();
              data = JSON.stringify({
                'results': content
              });
              resp.writeHead(200, {
                "Content-Type": "text/json"
              });
              resp.write(data, "utf8");
              return resp.end();
            });
            _results = [];
            for (_i = 0, _len = content.length; _i < _len; _i++) {
              weibo = content[_i];
              _results.push(analyze(weibo, content));
            }
            return _results;
          }
        });
      });
      client.on('error', function(e) {
        return console.log("Request weibo with error " + e.message);
      });
      return client.end();
    }
  });

  server.listen(8000);

  analyze = function(weibo, weibos) {
    var client, list, options, user;
    list = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = users.length; _i < _len; _i++) {
        user = users[_i];
        if (user['id'] === weibo['from_user_id']) {
          _results.push(user);
        }
      }
      return _results;
    })();
    if (list.length === 0) {
      options = {
        host: weibo_host_v2,
        path: "/2/users/show.json?access_token=" + access_token + "&uid=" + weibo['from_user_id']
      };
      client = https.request(options, function(res) {
        var raw;
        res.setEncoding('utf8');
        raw = "";
        res.on('data', function(chunk) {
          return raw += chunk;
        });
        return res.on('end', function() {
          var data;
          data = JSON.parse(raw);
          if (data != null) {
            users.push(data);
            weibo['user_followers_count'] = data['followers_count'];
            if (((function() {
              var _i, _len, _results;
              _results = [];
              for (_i = 0, _len = weibos.length; _i < _len; _i++) {
                weibo = weibos[_i];
                if (weibo.hasOwnProperty('user_followers_count')) {
                  _results.push(weibo);
                }
              }
              return _results;
            })()).length === weibos.length) {
              return emitter.emit("all-user-info-ready");
            }
          }
        });
      });
      client.on('error', function(e) {
        weibo['user_followers_count'] = -1;
        return console.log("Request weibo with error " + e.message);
      });
      return client.end();
    } else {
      return weibo['user_followers_count'] = list[0]['followers_count'];
    }
  };

}).call(this);
